fbcp added

diff --git a/MHS35-show b/MHS35-show
--- a/MHS35-show
+++ b/MHS35-show
@@ -52,6 +52,54 @@ if test "$nodeplatform" = "raspberrypi"
       echo "this is not raspberrypi kernel, no need to update touch configure, reboot"
 fi
 
+
+# Install cmake and other build tool dependencies for fbcp
+
+if [[ "$deb_version" < "12.10" ]]; then
+sudo apt-get update
+fi
+#FBCP install
+wget --spider -q -o /dev/null --tries=1 -T 10 https://cmake.org/
+if [ $? -eq 0 ]; then
+#sudo apt-get update
+sudo apt-get install cmake libraspberrypi-dev -y 2> error_output.txt # need to find a workaround as it removes the raspi-config utility
+result=`cat ./error_output.txt`
+echo -e "\033[31m$result\033[0m"
+grep -q "^E:" ./error_output.txt
+type cmake > /dev/null 2>&1
+if [ $? -eq 0 ]; then
+sudo rm -rf rpi-fbcp
+wget --spider -q -o /dev/null --tries=1 -T 10 https://github.com
+if [ $? -eq 0 ]; then
+sudo git clone https://github.com/tasanakorn/rpi-fbcp  # tries to clone from repo
+if [ $? -ne 0 ]; then
+echo "download fbcp failed, copy native fbcp!!!"
+sudo cp -r ./usr/rpi-fbcp .
+fi
+else
+echo "bad network, copy native fbcp!!!"
+sudo cp -r ./usr/rpi-fbcp .
+fi
+sudo mkdir ./rpi-fbcp/build
+cd ./rpi-fbcp/build/
+sudo cmake ..
+sudo make  # build fbcp application
+sudo install fbcp /usr/local/bin/fbcp
+cd - > /dev/null
+type fbcp > /dev/null 2>&1
+if [ $? -eq 0 ]; then
+if [[ "$deb_version" < "12.1" ]]; then
+sudo cp -rf ./usr/99-fbturbo-fbcp.conf  /usr/share/X11/xorg.conf.d/99-fbturbo.conf # copies fbcp conf file
+fi
+sudo cp -rf ./etc/rc.local /etc/rc.local # Enables the fbcp in the rc.local file
+fi
+else
+echo "install cmake error!!!!"
+fi
+else
+echo "bad network, can't install cmake!!!"
+fi
+
 sudo sync
 sudo sync
 sleep 1
